"""Provider-neutral semantic interpretation of physical table headers."""

from averon_import.services.ocr.semantics.column_mapper import (
    HeaderSemanticMapper,
    map_semantic_header,
)
from averon_import.services.ocr.semantics.header_evidence import (
    HeaderCellEvidence,
    HeaderMappingResult,
    HeaderRegionEvidence,
    HeaderSourceCell,
    SemanticCandidate,
)
from averon_import.services.ocr.semantics.header_normalizer import HeaderCellNormalizer
from averon_import.services.ocr.semantics.context_evidence import (
    BoundedFamilyContext,
    ContextRegionEvidence,
)
from averon_import.services.ocr.semantics.family_classifier import (
    AMBIGUOUS as AMBIGUOUS_FAMILY,
    OTHER_TABLE,
    SUPPORTED_SPECIFICATION,
    DEFAULT_TABLE_FAMILY_CLASSIFIER,
    FamilyEvidence,
    TableFamilyAssessment,
    TableFamilyClassifier,
)
from averon_import.services.ocr.semantics.schema_gate import (
    SchemaAssessment,
    SchemaGate,
    SchemaGateEvidence,
    DEFAULT_SCHEMA_GATE,
    UNKNOWN as UNKNOWN_SCHEMA,
)
from averon_import.services.ocr.semantics.observed_schema import (
    ObservedColumn,
    ObservedSchema,
    TypedMeasurement,
)
from averon_import.services.ocr.semantics.schema_profiles import (
    Applicability,
    DEFAULT_SCHEMA_PROFILE_MATCHER,
    DEFAULT_SCHEMA_PROFILES,
    ELEMENT_ASSEMBLY_SPECIFICATION,
    EQUIPMENT_MATERIAL_SPECIFICATION,
    MATERIAL_MEASURE_SPECIFICATION,
    ProfileMatchResult,
    RowContract,
    SchemaProfileMatcher,
    SpecificationSchemaProfile,
    UNKNOWN_SPEC_SCHEMA,
)
from averon_import.services.ocr.semantics.row_evidence import (
    RoleCandidate,
    RowRelationAssessment,
    RowRelationState,
    RowRelationType,
    RowRole,
    RowRoleAssessment,
    RowRoleCandidate,
    RowRoleState,
    SemanticReviewImpact,
    RowQualifier,
)
from averon_import.services.ocr.semantics.semantic_table import (
    DispositionValidation,
    FieldOrigin,
    FieldValueCandidate,
    InvalidDispositionState,
    LogicalFieldValue,
    LogicalSpecificationItem,
    ResolvedPhysicalDisposition,
    SemanticConservationReport,
    SemanticOrigin,
    SemanticTableIR,
    SourceFieldFragment,
    TableAnalysisContext,
    ValueCandidate,
    evaluate_semantic_conservation,
)
from averon_import.services.ocr.semantics.functional_analyzer import (
    EvidenceTier,
    FunctionalEvidenceGraph,
    TableFunctionalAnalyzer,
    physical_table_ir_from_snapshot,
)
from averon_import.services.ocr.semantics.row_relation_analyzer import RowRelationAnalyzer
from averon_import.services.ocr.semantics.row_semantics_resolver import GlobalRowSemanticsResolver
from averon_import.services.ocr.semantics.semantic_projection import (
    StructuredReconstructionResult,
    project_semantic_table,
    semantic_table_authoritative_enabled,
)

__all__ = [
    "HeaderCellEvidence",
    "HeaderCellNormalizer",
    "HeaderMappingResult",
    "HeaderRegionEvidence",
    "HeaderSemanticMapper",
    "HeaderSourceCell",
    "SemanticCandidate",
    "map_semantic_header",
    "BoundedFamilyContext",
    "ContextRegionEvidence",
    "FamilyEvidence",
    "TableFamilyAssessment",
    "TableFamilyClassifier",
    "DEFAULT_TABLE_FAMILY_CLASSIFIER",
    "SUPPORTED_SPECIFICATION",
    "OTHER_TABLE",
    "AMBIGUOUS_FAMILY",
    "SchemaAssessment",
    "SchemaGate",
    "SchemaGateEvidence",
    "DEFAULT_SCHEMA_GATE",
    "UNKNOWN_SCHEMA",
    "ObservedColumn",
    "ObservedSchema",
    "TypedMeasurement",
    "Applicability",
    "DEFAULT_SCHEMA_PROFILE_MATCHER",
    "DEFAULT_SCHEMA_PROFILES",
    "ELEMENT_ASSEMBLY_SPECIFICATION",
    "EQUIPMENT_MATERIAL_SPECIFICATION",
    "MATERIAL_MEASURE_SPECIFICATION",
    "ProfileMatchResult",
    "RowContract",
    "SchemaProfileMatcher",
    "SpecificationSchemaProfile",
    "UNKNOWN_SPEC_SCHEMA",
    "RoleCandidate",
    "RowRoleCandidate",
    "RowRole",
    "RowQualifier",
    "RowRoleAssessment",
    "RowRoleState",
    "SemanticReviewImpact",
    "RowRelationAssessment",
    "RowRelationState",
    "RowRelationType",
    "DispositionValidation",
    "InvalidDispositionState",
    "FieldOrigin",
    "SemanticOrigin",
    "ValueCandidate",
    "FieldValueCandidate",
    "SourceFieldFragment",
    "LogicalFieldValue",
    "LogicalSpecificationItem",
    "ResolvedPhysicalDisposition",
    "SemanticConservationReport",
    "SemanticTableIR",
    "TableAnalysisContext",
    "evaluate_semantic_conservation",
    "EvidenceTier",
    "FunctionalEvidenceGraph",
    "TableFunctionalAnalyzer",
    "physical_table_ir_from_snapshot",
    "RowRelationAnalyzer",
    "GlobalRowSemanticsResolver",
    "StructuredReconstructionResult",
    "project_semantic_table",
    "semantic_table_authoritative_enabled",
]
